### PR TITLE
Upgrade to Launchpad

### LINKED ISSUE #302: client.getNonce() no longer works with SDK v0.39.0
Running `getNonce` produces the following error:

```
vue.runtime.esm.js?2b0e:1888 TypeError: str.toLowerCase is not a function
    at __decode (index.js?bf2b:78)
    at Object.decode (index.js?bf2b:116)
    at Function.decode (bech32.js?2ead:30)
    at Object.decodeBech32Pubkey (pubkey.js?904b:28)
    at SigningCosmosClient.getAccount (cosmosclient.js?b5a7:98)
    at async SigningCosmosClient.getNonce (cosmosclient.js?b5a7:78)
```

I'm thinking the problem is that the client API has changed `http://localhost:1317/auth/accounts/cosmos12x4undlwc0...`

v0.38.4:

```json
{
  "height": "2",
  "result": {
    "type": "cosmos-sdk/Account",
    "value": {
      "address": "cosmos1c2ju5u3wx57zv8ceehpqcvh7nusc4vgt67dg3q",
      "coins": [
        {
          "denom": "token",
          "amount": "1000"
        }
      ],
      "public_key": "cosmospub1addwnpepqttcheas8x7p4f9km0kc9qgcguk9lkdery744tujnc2dshtjfqxh59l6gsa",
      "account_number": 2,
      "sequence": 1
    }
  }
}
```

v0.39.0:

```json
{
  "height": "8",
  "result": {
    "type": "cosmos-sdk/Account",
    "value": {
      "address": "cosmos12x4up7dhsndlwc06t4p3jfn8zvz6x3t72fp30v",
      "coins": [
        {
          "denom": "token",
          "amount": "1000"
        }
      ],
      "public_key": {
        "type": "tendermint/PubKeySecp256k1",
        "value": "AvjV2kYc2DldNZ7XEqGzyoyv+sd6qJCyEps7APBE+ugV"
      },
      "account_number": "2",
      "sequence": "1"
    }
  }
}
```

### LINKED ISSUE #306: Drop Cosmos SDK 0.38 support in favour of Launchpad
Staring with wasmd 0.10, our local test chain will be based on Cosmos SDK 0.39 ([Launchpad](https://blog.cosmos.network/launchpad-a-pre-stargate-stable-version-of-the-cosmos-sdk-e0c58d8c4e24)). This is an LTS version of Cosmos SDK many projects use. We assume a Cosmos SDK 0.38 client will not be needed anymore (please let us know if you are willing to fund Cosmos SDK 0.38 client maintenance).

- [ ] Rename package @cosmjs/sdk38 to @cosmjs/launchpad
- [ ] Upgrade local test chain to wasmd 0.10/Cosmos SDK 0.39
- [ ] Link this intro article in the package description: https://blog.cosmos.network/launchpad-a-pre-stargate-stable-version-of-the-cosmos-sdk-e0c58d8c4e24
- [ ] Release CosmJS 0.22.0
- [ ] Deprecate @cosmjs/sdk38 on npm as unmaintained

### PR DESCRIPTION
**Pull request by webmaster128**
~Based on #314~

Closes #306

Dependencies

- [x] Update after #318 is merged (which adds a vilidator address to cosmwasm tests)
- [x] Update after #314 is merged
- [x] Get CORS setting (https://github.com/CosmWasm/wasmd/issues/222)

### CODE REVIEW

**Comment by ethanfrey** [comment]
Now that https://github.com/CosmWasm/wasmd/issues/222 is solved, is this blocked on any external requirement?

I guess just me tagging a stable `v0.10.0-beta` release of `wasmd` with these fixes. Anything else I can help with?

**Comment by webmaster128** [comment]
> I guess just me tagging a stable `v0.10.0-beta` release of `wasmd` with these fixes. Anything else I can help with?

Perfect. I just need that tag ob dockerhub. Then we should have everything to continue.

**Comment by ethanfrey** [comment]
`v0.10.0-beta1` is pushed. I will push a `beta2` today or tomorrow that should close all known issues and will provide last validation before CosmWasm `v0.10.0`

File: packages/cosmwasm/src/lcdapi/wasm.spec.ts [hunk 1]
```diff
@@ -335,7 +335,7 @@ describe("wasm", () => {
       // upload data
       const hackatom = getHackatom();
       const result = await uploadContract(client, wallet, hackatom);
-      expect(result.code).toBeFalsy();
+      assert(!result.code);
```
Comment (ethanfrey) [inline packages/cosmwasm/src/lcdapi/wasm.spec.ts:338]: why is this better?

we are checking for `0` or `undefined` if I understand

File: packages/cosmwasm/src/lcdapi/wasm.spec.ts [hunk 2]
```diff
@@ -430,6 +422,49 @@ describe("wasm", () => {
       expect(await client.wasm.getContractInfo(nonExistentAddress)).toBeNull();
     });
 
+    it("can list contract history", async () => {
```
Comment (ethanfrey) [inline packages/cosmwasm/src/lcdapi/wasm.spec.ts:425]: nice

File: packages/launchpad/src/lcdapi/lcdclient.spec.ts [hunk 3]
```diff
@@ -47,51 +35,39 @@ describe("LcdClient", () => {
...
-      wasm: {
-        listCodeInfo: () => Promise<readonly CodeInfo[]>;
+    interface BankExtension {
+      readonly bank: {
+        readonly balances: (address: string) => Promise<BankBalancesResponse>;
       };
     }
 
-    function setupWasmExtension(base: LcdClient): WasmExtension {
+    function setupBankExtension(base: LcdClient): BankExtension {
```
Comment (ethanfrey) [inline packages/launchpad/src/lcdapi/lcdclient.spec.ts:65]: Why is this in the test code?
Don't we have such an implementation in the non-test (production) code?

File: scripts/wasmd/send_first.js [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+
+const httpUrl = "http://localhost:1317";
+const faucet = {
+  mnemonic:
+    "economy stock theory fatal elder harbor betray wasp final emotion task crumble siren bottom lizard educate guess current outdoor pair theory focus wife stone",
+  address0: "cosmos1pkptre7fdkl6gfrzlesjjvhxhlc3r4gmmk8rs6",
+};
+
+async function main() {
+  const wallet = await Secp256k1Wallet.fromMnemonic(faucet.mnemonic);
```
Comment (ethanfrey) [inline scripts/wasmd/send_first.js:16]: good minimal example of how to use the wallet in tests

Comment (ethanfrey) [reply scripts/wasmd/send_first.js:16]: maybe link this (or other such example) from a README

File: scripts/wasmd/template/.wasmcli/cosmos1fa7hj49pf8uzc4m0lw5swjhhl5th2484dc82dl.address [hunk 5]
```diff
@@ -0,0 +1 @@
+eyJhbGciOiJQQkVTMi1IUzI1NitBMTI4S1ciLCJjcmVhdGVkIjoiMjAyMC0wNy0yMyAxNTowNTo0OC4yMDIyMjEgKzAwMDAgVVRDIG09KzAuNDA3MTQ2NDAxIiwiZW5jIjoiQTI1NkdDTSIsInAyYyI6ODE5MiwicDJzIjoiZXhEVEM1dGVraTVyMDg4ZyJ9.AluhnvIPJAJZZIUwCATLZ2eQNBy-bqUMOwa1QVokRPU4MWOsuxx-TQ.3vXpP5cMQEXdSBko.l5BzPkI5_DUm-iUBM9T9po-9YXYmGK62eieeFVA_WzESZPYxk51fQq_8DCdhh6Y6DhmmvQXPv3hjqQgIgdxPRBFlJwNawrqLElWIVuiS02tAjwQXAw6to0sdNtJc5r8Fzr82aD_lRMDiJ5ZoJ6i3wHLgmfwtOH0JdGwGFwiEQYuWX0SK0Ms2LHUydmsriX6MbHik24R061Qc3dR0GfclCb9dP_jRvXBhen8EJyt3cM3opYZ5lqDcLv_OQnDaFb4.Ctl177TJVkOiSYSaG3IBBg
```
Comment (ethanfrey) [inline scripts/wasmd/template/.wasmcli/cosmos1fa7hj49pf8uzc4m0lw5swjhhl5th2484dc82dl.address:1]: I think there is a typo here :stuck_out_tongue: 

just kidding... had to saw something when scrolling over tons of auto-gen code

File: scripts/wasmd/template/.wasmd/config/app.toml [hunk 6]
```diff
@@ -8,6 +8,17 @@
 # specified in this config (e.g. 0.25token1;0.0001token2).
 minimum-gas-prices = ""
 
+# default: the last 100 states are kept in addition to every 500th state; pruning at 10 block intervals
```
Comment (ethanfrey) [inline scripts/wasmd/template/.wasmd/config/app.toml:11]: :+1:

File: packages/cosmwasm/src/lcdapi/wasm.spec.ts (hunk 1 above)
Comment (webmaster128) [reply packages/cosmwasm/src/lcdapi/wasm.spec.ts:338]: Because `assert` throws if the condition is falsy, `expect` reports an error an continues. But in case the transaction failed, all the following checks are pointless and just hide the problem.

File: packages/launchpad/src/lcdapi/lcdclient.spec.ts (hunk 3 above)
Comment (webmaster128) [reply packages/launchpad/src/lcdapi/lcdclient.spec.ts:65]: We have, but we need to reduce dependencies. Otherwise lcdclient depends on bank extension and bank extension depends on lcdclient. Having a wasm dependency here before was a huge upgrade pain.

File: packages/launchpad/src/lcdapi/staking.spec.ts [hunk 7]
```diff
@@ -29,6 +30,9 @@ describe("StakingExtension", () => {
     amount: coins(25000, "ucosm"),
     gas: "1500000", // 1.5 million
   };
+  const consesnsusPubkey =
```
Comment (willclarktech) [inline packages/launchpad/src/lcdapi/staking.spec.ts:33]: `consensusPubkey`
