### ISSUE TITLE
Cannot find name 'loadOrCreateMnemonic'.

### ISSUE THREAD

**Issue by athenawisdoms** [CosmWasm/cosmjs#458]
Hi, I installed `cosmjs-cli` globally using `npm install -g @cosmjs/cli` in order to follow the [official CosmWasm tutorial](https://docs.cosmwasm.com/getting-started/interact-with-contract.html#node-console).

However, when I try to use the function `loadOrCreateMnemonic`, there is an error

> error TS2304: Cannot find name 'loadOrCreateMnemonic'.

How can we fix this problem so that we can continue the tutorial?

```
$ cosmwasm-cli --version
0.23.0

$ cosmwasm-cli 
Initializing session for you. Have fun!
Available imports:
  * axios
  * fs
  * from @cosmjs/cosmwasm: Account, Block, BlockHeader, Code, CodeDetails, Contract, ContractCodeHistoryEntry, CosmWasmClient, GetSequenceResult, SearchByHeightQuery, SearchByIdQuery, SearchBySentFromOrToQuery, SearchByTagsQuery, SearchTxQuery, SearchTxFilter, ExecuteResult, CosmWasmFeeTable, InstantiateResult, SigningCosmWasmClient, UploadMeta, UploadResult
  * from @cosmjs/crypto: Bip39, Ed25519, Ed25519Keypair, EnglishMnemonic, HdPath, Random, Secp256k1, Sha256, Sha512, Slip10, Slip10Curve, Slip10RawIndex
  * from @cosmjs/encoding: fromAscii, fromBase64, fromHex, fromUtf8, toAscii, toBase64, toHex, toUtf8, Bech32
  * from @cosmjs/launchpad: coin, coins, decodeAminoPubkey, decodeBech32Pubkey, encodeAminoPubkey, encodeBech32Pubkey, encodeSecp256k1Pubkey, encodeSecp256k1Signature, logs, makeCosmoshubPath, makeSignDoc, makeStdTx, IndexedTx, BroadcastTxResult, Coin, CosmosClient, GasLimits, GasPrice, Msg, MsgDelegate, MsgSend, LcdClient, OfflineSigner, PubKey, pubkeyToAddress, Secp256k1HdWallet, SigningCosmosClient, StdFee, StdSignDoc, StdTx
  * from @cosmjs/math: Decimal, Int53, Uint32, Uint53, Uint64
  * from @cosmjs/utils: assert, arrayContentEquals, sleep
>> const fredSeed = loadOrCreateMnemonic("fred.key");
../../../../../../../usr/lib/node_modules/@cosmjs/cli/[eval].ts:11:18 - error TS2304: Cannot find name 'loadOrCreateMnemonic'.

11 const fredSeed = loadOrCreateMnemonic("fred.key");
                    ~~~~~~~~~~~~~~~~~~~~

undefined
>> 

```

Thank you!

**Comment by webmaster128** [comment]
`loadOrCreateMnemonic` is not available in thee CLI directly but in a script that is loaded. So you have to call

```
cosmwasm-cli --init https://raw.githubusercontent.com/CosmWasm/testnets/master/coralnet/cli_helper.ts
```

--------------

The next problem you will encounter is that this script only works with CosmJS 0.22.x. So you have to install version `^0.22`. An updated script will follow.

**Comment by webmaster128** [comment]
I am updating the docs to fix the version here: https://github.com/CosmWasm/docs/pull/111

However, the proper solution is to upgrade to 0.23 and adapt the scripts.

**Comment by athenawisdoms** [comment]
@webmaster128 Tried the command you suggested, but there is now a different error:

```
$ cosmwasm-cli --init https://raw.githubusercontent.com/CosmWasm/testnets/master/coralnet/cli_helper.ts
Initializing session for you. Have fun!
Available imports:
  * axios
  * fs
  * from @cosmjs/cosmwasm: Account, Block, BlockHeader, Code, CodeDetails, Contract, ContractCodeHistoryEntry, CosmWasmClient, GetSequenceResult, SearchByHeightQuery, SearchByIdQuery, SearchBySentFromOrToQuery, SearchByTagsQuery, SearchTxQuery, SearchTxFilter, ExecuteResult, CosmWasmFeeTable, InstantiateResult, SigningCosmWasmClient, UploadMeta, UploadResult
  * from @cosmjs/crypto: Bip39, Ed25519, Ed25519Keypair, EnglishMnemonic, HdPath, Random, Secp256k1, Sha256, Sha512, Slip10, Slip10Curve, Slip10RawIndex
  * from @cosmjs/encoding: fromAscii, fromBase64, fromHex, fromUtf8, toAscii, toBase64, toHex, toUtf8, Bech32
  * from @cosmjs/launchpad: coin, coins, decodeAminoPubkey, decodeBech32Pubkey, encodeAminoPubkey, encodeBech32Pubkey, encodeSecp256k1Pubkey, encodeSecp256k1Signature, logs, makeCosmoshubPath, makeSignDoc, makeStdTx, IndexedTx, BroadcastTxResult, Coin, CosmosClient, GasLimits, GasPrice, Msg, MsgDelegate, MsgSend, LcdClient, OfflineSigner, PubKey, pubkeyToAddress, Secp256k1HdWallet, SigningCosmosClient, StdFee, StdSignDoc, StdTx
  * from @cosmjs/math: Decimal, Int53, Uint32, Uint53, Uint64
  * from @cosmjs/utils: assert, arrayContentEquals, sleep
>> ../../../../../../../usr/lib/node_modules/@cosmjs/cli/[eval].ts:28:61 - error TS2304: Cannot find name 'FeeTable'.

28 const buildFeeTable = (feeToken: string, gasPrice: number): FeeTable => {
                                                               ~~~~~~~~
../../../../../../../usr/lib/node_modules/@cosmjs/cli/[eval].ts:107:49 - error TS2304: Cannot find name 'Secp256k1Wallet'.

107 const buildWallet = (mnemonic: string): Promise<Secp256k1Wallet> => {
                                                    ~~~~~~~~~~~~~~~
../../../../../../../usr/lib/node_modules/@cosmjs/cli/[eval].ts:108:10 - error TS2552: Cannot find name 'Secp256k1Wallet'. Did you mean 'Secp256k1HdWallet'?

108   return Secp256k1Wallet.fromMnemonic(mnemonic, makeCosmoshubPath(0), defaultOptions.bech32prefix);
             ~~~~~~~~~~~~~~~
```

However, using `npx` works:

```
$ npx @cosmjs/cli@^0.22 --init https://raw.githubusercontent.com/CosmWasm/testnets/master/coralnet/cli_helper.ts
npx: installed 84 in 4.394s
Initializing session for you. Have fun!
Available imports:
  * axios
  * fs
  * from @cosmjs/cosmwasm: Account, Block, BlockHeader, Code, CodeDetails, Contract, ContractCodeHistoryEntry, CosmWasmClient, GetSequenceResult, SearchByHeightQuery, SearchByIdQuery, SearchBySentFromOrToQuery, SearchByTagsQuery, SearchTxQuery, SearchTxFilter, ExecuteResult, FeeTable, InstantiateResult, SigningCosmWasmClient, UploadMeta, UploadResult
  * from @cosmjs/crypto: Bip39, Ed25519, Ed25519Keypair, EnglishMnemonic, Random, Secp256k1, Sha256, Sha512, Slip10, Slip10Curve, Slip10RawIndex
  * from @cosmjs/encoding: fromAscii, fromBase64, fromHex, fromUtf8, toAscii, toBase64, toHex, toUtf8, Bech32
  * from @cosmjs/launchpad: coin, coins, decodeAminoPubkey, decodeBech32Pubkey, encodeAminoPubkey, encodeBech32Pubkey, encodeSecp256k1Pubkey, encodeSecp256k1Signature, logs, makeCosmoshubPath, makeSignBytes, IndexedTx, Coin, CosmosClient, Msg, MsgDelegate, MsgSend, LcdClient, OfflineSigner, PostTxResult, PubKey, pubkeyToAddress, Secp256k1Wallet, SigningCosmosClient, StdFee, StdTx
  * from @cosmjs/math: Decimal, Int53, Uint32, Uint53, Uint64
  * from @cosmjs/utils: assert, arrayContentEquals, sleep
>> 
```

Why does the globally installed `cosmwasm-cli` v0.23.0 not work?

I'm at least happy that the `npx` command allowed me to continue the tutorial!

**Comment by webmaster128** [comment]
The script you are executing (https://raw.githubusercontent.com/CosmWasm/testnets/master/coralnet/cli_helper.ts) was written for 0.22 and uses APIs that changed or don't exist anymore in 0.23. You can install the CLI globally, no problem. But you need to ensure to install 0.22.x.

The proper solution here is to update the script to work with the latest version of CosmJS.

**Comment by athenawisdoms** [comment]
Thanks!
