### PR TITLE
Let /auth/accounts/<address> client support 0.37-0.39 format

### LINKED ISSUE #302: client.getNonce() no longer works with SDK v0.39.0
Running `getNonce` produces the following error:

```
vue.runtime.esm.js?2b0e:1888 TypeError: str.toLowerCase is not a function
    at __decode (index.js?bf2b:78)
    at Object.decode (index.js?bf2b:116)
    at Function.decode (bech32.js?2ead:30)
    at Object.decodeBech32Pubkey (pubkey.js?904b:28)
    at SigningCosmosClient.getAccount (cosmosclient.js?b5a7:98)
    at async SigningCosmosClient.getNonce (cosmosclient.js?b5a7:78)
```

I'm thinking the problem is that the client API has changed `http://localhost:1317/auth/accounts/cosmos12x4undlwc0...`

v0.38.4:

```json
{
  "height": "2",
  "result": {
    "type": "cosmos-sdk/Account",
    "value": {
      "address": "cosmos1c2ju5u3wx57zv8ceehpqcvh7nusc4vgt67dg3q",
      "coins": [
        {
          "denom": "token",
          "amount": "1000"
        }
      ],
      "public_key": "cosmospub1addwnpepqttcheas8x7p4f9km0kc9qgcguk9lkdery744tujnc2dshtjfqxh59l6gsa",
      "account_number": 2,
      "sequence": 1
    }
  }
}
```

v0.39.0:

```json
{
  "height": "8",
  "result": {
    "type": "cosmos-sdk/Account",
    "value": {
      "address": "cosmos12x4up7dhsndlwc06t4p3jfn8zvz6x3t72fp30v",
      "coins": [
        {
          "denom": "token",
          "amount": "1000"
        }
      ],
      "public_key": {
        "type": "tendermint/PubKeySecp256k1",
        "value": "AvjV2kYc2DldNZ7XEqGzyoyv+sd6qJCyEps7APBE+ugV"
      },
      "account_number": "2",
      "sequence": "1"
    }
  }
}
```

### LINKED ISSUE #312: `getAccount()` method fails on the latest version of cosmos-sdk
https://github.com/CosmWasm/cosmjs/blob/master/packages/sdk38/src/cosmosclient.ts#L222

In the current implementation, `getAccount()` method expects that the public key is delivered as bech32. I'm not sure which version of the cosmos-sdk the changes were made, but accounts on the newer versions of the SDK return as follows:

```
{"height":"2724145","result":{"type":"cosmos-sdk/Account","value":{"address":"cosmos1ntck6f6534u630q87jpamettes6shwgddag769","coins":[{"denom":"uatom","amount":"489300"}],"public_key":{"type":"tendermint/PubKeySecp256k1","value":"Aqb4yDyanddEzrLjbTzhBsowmh6uC6InWAMRmCISoYt5"},"account_number":"58220","sequence":"6"}}}
```

Thus, bech32 decoding will fail and `getAccount()` method doesn't work.
And, because the above public key type is the same as https://github.com/CosmWasm/cosmjs/blob/master/packages/sdk38/src/types.ts#L39, it is not needed to parse them.

### PR DESCRIPTION
**Pull request by webmaster128**
Based on #313.

This allows us to use one LCD API client for Comsos SDK 0.37-0.39.

Closes #302
Closes #312

### CODE REVIEW

File: packages/sdk38/src/lcdapi/auth.ts [hunk 1]
```diff
@@ -1,22 +1,58 @@
...
+   * and changed back to string in Cosmos SDK 0.39 ([2]).
+   *
+   * [1]: https://github.com/cosmos/cosmos-sdk/pull/5280
+   * [2]: https://github.com/cosmos/cosmos-sdk/pull/6749
+   */
+  readonly account_number: number | string;
+  /**
+   * The sequence number for replay protection.
+   *
+   * This was string encoded in Cosmos SDK 0.37, changed to number in Cosmos SDK 0.38 ([1])
```
Comment (ethanfrey) [inline packages/sdk38/src/lcdapi/auth.ts:42]: :facepalm: 

Good to handle this all... just 0.38 what?

File: packages/sdk38/src/lcdapi/auth.ts [hunk 2]
```diff
@@ -1,22 +1,58 @@
 /* eslint-disable @typescript-eslint/naming-convention */
 import { Coin } from "../coins";
+import { PubKey } from "../types";
 import { LcdClient } from "./lcdclient";
 
-export interface CosmosSdkAccount {
+/**
+ * A Cosmos SDK base account.
+ *
+ * This type described the base account representation as returned
```
Comment (willclarktech) [inline packages/sdk38/src/lcdapi/auth.ts:9]: Typo: "describes"?

File: packages/sdk38/src/lcdapi/auth.ts [hunk 3]
```diff
@@ -1,22 +1,58 @@
...
   readonly coins: readonly Coin[];
-  /** Bech32 encoded pubkey */
-  readonly public_key: string;
-  readonly account_number: number;
-  readonly sequence: number;
+  /**
+   * The public key of the account. This is not available on-chain as long as the account
+   * did not send a transaction.
+   *
+   * This was a type/value object in Cosmos SDK 0.37, changed to bach32 in Cosmos SDK 0.38 ([1])
```
Comment (willclarktech) [inline packages/sdk38/src/lcdapi/auth.ts:22]: Typo: "bech32"

File: packages/sdk38/src/lcdapi/utils.ts [hunk 4]
```diff
@@ -0,0 +1,38 @@
+import { Uint64 } from "@cosmjs/math";
+
+import { decodeBech32Pubkey } from "../pubkey";
+import { PubKey } from "../types";
+
+/**
+ * Convers an integer expressed as number or string to a number.
```
Comment (willclarktech) [inline packages/sdk38/src/lcdapi/utils.ts:7]: Typo: "Converts"

File: packages/sdk38/src/lcdapi/utils.ts [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+ *
+ * This is needed for supporting Comsos SDK 0.37/0.38/0.39 with one client.
+ */
+export function uint64ToNumber(input: number | string): number {
+  const value = typeof input === "number" ? Uint64.fromNumber(input) : Uint64.fromString(input);
+  return value.toNumber();
+}
+
+/**
+ * Convers an integer expressed as number or string to a number.
```
Comment (willclarktech) [inline packages/sdk38/src/lcdapi/utils.ts:18]: Typo: "Converts"
